spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

server:
  port: 9000

app:
  keycloak:
    realm: spring
    serverUrl: http://localhost:9082

services:
  collectionServiceUrl: "http://localhost:8080"
  usersServiceUrl: "http://localhost:6700"

logging:
  level:
    org.springframework:
      security: DEBUG
      cloud.gateway: DEBUG
